version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        JAR_FILE: target/streamfinder-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      DB_URL: host.docker.internal:27017
      CORS_ALLOWED_ORIGINS: http://localhost:3000

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      API_URL: http://localhost:8080
